[package]
name = "eruptrace_scene"
version = "0.1.0"
authors = ["Adam GÄ…sior"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
itertools = "0.10"
serde_json = "1.0"
nalgebra-glm = "0.16"
std140 = "0.2"
